export const siteConfig = {
  name: "D&C MediaHouse",
  hero: {
    topline: "Cinematic Excellence",
    headline: "We Don't Shoot Videos. We Tell Stories.",
    subheadline: "Event | Brands | Weddings",
    video: "hero/showreel/playlist.m3u8",
    primaryButton: {
      text: "Explore Films",
      link: "#work"
    },
    secondaryButton: {
      text: "CONNECT WITH US",
      link: "#contact"
    }
  },
  playbook: {
    main: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9",
    boards: {
      showreels: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/8Emrazrov52NdteizRg8kXTw",
      weddings: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/jWYfd8r9eQStaknuLoLmsuLz",
      brands: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/1DkvHvBcMjeuEr4mbWEwkVeB",
      corporates: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/KzBPW7QtrxgKnkt7sh6sLam9",
      concerts: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/Tpj5aVQG5jvj7R1dZKjoY943",
      lifestyle: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/7A2dacAESQB64hhbo73KC7zL",
      foodDrinks: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/Dq5EFdKUAWCRBp8Dwae7jrcw",
      artAesthetics: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/smxv4YpsZRB8iQCw8Lyycqeh",
      carsAutomobiles: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/8uetEY2BnTLnHA4ZhcNFF3nh",
      realEstates: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/CSv7yFmqMkojfHPfDE7RLDjw",
      socialEvents: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/WuZEcgkxmKxPCR6MiDkocNhw",
      makeup: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/1U1K4JpMpLqN15i8CFBsY72J",
      influencers: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/3cTDed3RnxNoUDvTS3Spsj19",
      fashion: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/Cug7Xezvi6LfhSAM2TWRZkor",
      liveEvents: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/1dpu3z33zeN1ATJqJruPgZZk",
      band: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/s3eT5CscJ14VAL6EXYUKMwE4",
      portraits: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/ygAkQZap23ZVjDAoFqGWrbLC",
      newGigs: "https://www.playbook.com/s/heyloosk/LbCG9BCybsFn5djySvMFMbp9/MpzgB4mM9YJanuaqBMF4WH6z",
    }
  },
  portfolio: [
    {
      id: "1",
      title: "The Art of Fashion",
      category: "Brands",
      video: "work/commercial/Video-256/playlist.m3u8",
      thumbnail: "https://picsum.photos/seed/fashion/800/1200",
      aspect: "aspect-[3/4]",
      playbookBoard: "brands",
    },
    {
      id: "2",
      title: "Wedding Bliss",
      category: "Weddings",
      video: "work/commercial/Video-207/playlist.m3u8",
      thumbnail: "https://picsum.photos/seed/wedding/800/1200",
      aspect: "aspect-[4/5]",
      playbookBoard: "weddings",
    },
    {
      id: "3",
      title: "Urban Motion",
      category: "Event",
      video: "work/cinematic-films/Video-212/playlist.m3u8",
      thumbnail: "https://picsum.photos/seed/urban/800/1200",
      aspect: "aspect-[2/3]",
      playbookBoard: "liveEvents",
    },
    {
      id: "4",
      title: "Corporate Vision",
      category: "Brands",
      video: "work/commercial/Video-584/playlist.m3u8",
      thumbnail: "https://picsum.photos/seed/corp/800/1200",
      aspect: "aspect-[3/4]",
      playbookBoard: "corporates",
    },
    {
      id: "5",
      title: "Eternal Moments",
      category: "Weddings",
      video: "work/commercial/Video-584/playlist.m3u8",
      thumbnail: "https://picsum.photos/seed/love/800/1200",
      aspect: "aspect-[4/5]",
      playbookBoard: "weddings",
    },
    {
      id: "6",
      title: "The Director's Cut",
      category: "Event",
      video: "work/cinematic-films/Video-212/playlist.m3u8",
      thumbnail: "https://picsum.photos/seed/film/800/1200",
      aspect: "aspect-[2/3]",
      playbookBoard: "liveEvents",
      isDirectorCut: true
    },
    {
      id: "7",
      title: "Visionary Edit",
      category: "Event",
      video: "film/videoplayback (2)/playlist.m3u8",
      thumbnail: "https://picsum.photos/seed/vision/800/1200",
      aspect: "aspect-[3/4]",
      playbookBoard: "artAesthetics",
      isDirectorCut: true
    },
  ],
  gallery: [
    "gallery/3aa1286a125ff86a72ac57e37175cbd6.jpeg",
    "gallery/Ashish 2.png",
    "gallery/Billionaire Meet Sharma.jpg",
    "gallery/Critic Designs logo 3.png",
    "gallery/Dark Souls III.jpg",
    "gallery/Gordon Freeman.png",
    "gallery/Kingpin Final Boss (Meet).png",
    "gallery/Manhunt.jpg",
    "gallery/Screenshot 2022-02-17 220741.png",
    "gallery/Screenshot 2023-05-31 130135.png",
    "gallery/Screenshot 2023-10-01 224107.png",
    "gallery/Screenshot 2024-02-12 205801.png",
    "gallery/Screenshot 2024-05-24 211053.png",
    "gallery/Screenshot_20230702-231048.jpg",
    "gallery/mh-2-28-sly-1646063529.jpg",
  ],
  contact: {
    cta: "Let's Create Something Cinematic",
    email: "dcmediahouse.saksham@gmail.com",
    whatsapp: "https://wa.me/8130981018",
    instagram: "https://www.instagram.com/d.c_mediahouse",
  },
  brands: [
    { name: "Lakme", logo: "brands/Lakme.webp" },
    { name: "Fastrack", logo: "brands/Fastrack.jpg" },
    { name: "Vogue", logo: "brands/Vogue.webp" },
    { name: "Birkenstock", logo: "brands/Birkenstock.jpg" },
    { name: "Flirtatious", logo: "brands/Flirtatious.png" },
  ]
};
